; Generated by MicroWeldr - Streaming Subscriber
; Prusa Core One Plastic Welding G-code
; Output file: combined.gcode
;
; Process Overview:
; 1. Heat bed and calibrate
; 2. Heat nozzle and wait
; 3. Pause for plastic sheet insertion
; 4. Execute welding sequence
; 5. Cool down and finish
;
; Bed Temperature: 45°C
; Nozzle Temperature: 160°C
;

; Start heating bed to 45°C (heating during calibration)
M140 S45 ; Set bed temperature (start heating)

; Printer initialization
G90 ; Absolute positioning
M83 ; Relative extrusion
G28 ; Home all axes

; Heat bed and nozzle before bed leveling
M190 S45 ; Wait for bed temperature
M104 S160 ; Set nozzle temperature
M109 S160 ; Wait for nozzle temperature

; Bed leveling disabled

; Pause for user to insert plastic sheets
M117 Insert plastic sheets...
M0 ; Pause - Insert plastic sheets and press continue
M117 Starting welding sequence...

; Starting path: dxf_entity_0_0_249pts (normal)
G1 Z5.0 F3000 ; Move to high travel height
G1 X126.000 Y118.854 F3000 ; Move to start of welding
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.147 Y117.926 F3000 ; Move to start of path
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.574 Y117.089 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.239 Y116.426 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.077 Y116.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.832 Y115.722 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.562 Y115.384 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.263 Y114.988 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.930 Y114.537 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.558 Y114.034 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.144 Y113.482 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.684 Y112.885 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.174 Y112.246 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.610 Y111.571 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.991 Y110.862 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.314 Y110.124 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.577 Y109.364 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.777 Y108.584 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.914 Y107.791 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.987 Y106.990 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.995 Y106.185 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.939 Y105.382 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.818 Y104.586 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.634 Y103.803 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.387 Y103.037 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.079 Y102.293 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.712 Y101.577 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.289 Y100.892 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.813 Y100.243 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.286 Y99.635 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.711 Y99.072 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.093 Y98.556 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.436 Y98.092 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.743 Y97.682 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.020 Y97.329 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.271 Y97.035 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.500 Y96.803 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.715 Y95.972 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.929 Y95.141 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.144 Y94.310 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.358 Y93.479 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.573 Y92.648 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.787 Y91.817 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.002 Y90.986 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.216 Y90.155 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.431 Y89.324 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.646 Y88.493 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.860 Y87.662 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.075 Y86.831 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.289 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.231 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.174 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.116 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.058 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y85.125 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y84.250 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y83.375 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y82.500 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y81.625 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y80.750 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y79.875 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.200 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.400 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.600 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.800 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.000 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.200 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.400 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.600 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.800 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.000 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.200 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X125.400 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.600 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.800 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.000 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.200 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.400 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.600 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.800 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.000 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.200 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.400 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.600 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.800 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y79.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y79.875 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y80.750 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y81.625 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y82.500 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y83.375 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y84.250 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y85.125 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.942 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.884 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.826 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.769 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.711 Y86.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.925 Y86.831 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.140 Y87.662 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.354 Y88.493 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.569 Y89.324 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.784 Y90.155 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.998 Y90.986 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.213 Y91.817 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.427 Y92.648 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.642 Y93.479 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.856 Y94.310 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.071 Y95.141 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.285 Y95.972 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.500 Y96.803 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.729 Y97.035 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.980 Y97.329 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.257 Y97.682 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.564 Y98.092 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.907 Y98.556 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.289 Y99.072 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.714 Y99.635 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.187 Y100.243 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.711 Y100.892 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.288 Y101.577 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.921 Y102.293 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.613 Y103.037 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.366 Y103.803 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.182 Y104.586 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.061 Y105.382 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.005 Y106.185 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.013 Y106.990 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.086 Y107.791 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.223 Y108.584 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.423 Y109.364 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.686 Y110.124 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.009 Y110.862 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.390 Y111.571 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.826 Y112.246 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.316 Y112.885 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.856 Y113.482 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.442 Y114.034 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.070 Y114.537 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.737 Y114.988 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.438 Y115.384 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.168 Y115.722 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.923 Y116.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.761 Y116.426 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.426 Y117.089 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.853 Y117.926 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y118.854 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y119.664 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y120.474 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y121.284 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y122.093 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y122.903 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y123.713 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y124.522 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y125.332 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y126.142 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y126.951 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y127.761 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y128.571 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y129.381 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y130.190 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.000 Y131.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.978 Y131.809 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.913 Y132.616 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.804 Y133.419 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.652 Y134.214 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.457 Y135.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.220 Y135.774 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.942 Y136.535 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.623 Y137.279 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.264 Y138.005 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.867 Y138.710 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.432 Y139.393 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.961 Y140.052 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.455 Y140.684 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.916 Y141.288 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.345 Y141.862 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.724 Y142.453 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.103 Y143.044 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.483 Y143.635 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.862 Y144.227 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.241 Y144.818 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.621 Y145.409 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.000 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.800 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.600 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.400 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.200 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.000 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.800 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.600 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.400 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.200 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.000 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.800 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.600 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X125.400 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.200 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.000 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.800 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.600 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.400 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.200 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.000 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.800 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.600 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.400 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.200 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.000 Y146.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.379 Y145.409 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.759 Y144.818 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.138 Y144.227 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.517 Y143.635 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.897 Y143.044 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.276 Y142.453 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.655 Y141.862 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.084 Y141.288 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.545 Y140.684 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.039 Y140.052 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.568 Y139.393 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.133 Y138.710 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.736 Y138.005 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.377 Y137.279 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.058 Y136.535 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.780 Y135.774 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.543 Y135.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.348 Y134.214 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.196 Y133.419 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.087 Y132.616 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.022 Y131.809 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y131.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y130.190 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y129.381 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y128.571 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y127.761 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y126.951 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y126.142 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y125.332 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y124.522 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y123.713 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y122.903 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y122.093 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y121.284 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y120.474 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y119.664 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.000 Y118.854 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
; Completed path: dxf_entity_0_0_249pts

; Starting path: dxf_entity_1_0_15pts (normal)
G1 X131.875 Y99.223 F3000 ; Move to start of path
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.431 Y98.636 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.987 Y98.049 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.543 Y97.461 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.099 Y96.874 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.655 Y96.286 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.212 Y95.699 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.768 Y95.112 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X136.324 Y94.524 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X136.880 Y93.937 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X137.436 Y93.350 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X137.992 Y92.762 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X138.548 Y92.175 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X139.104 Y91.587 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X139.660 Y91.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
; Completed path: dxf_entity_1_0_15pts

; Starting path: dxf_entity_2_0_15pts (normal)
G1 X118.125 Y99.223 F3000 ; Move to start of path
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.569 Y98.636 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.013 Y98.049 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.457 Y97.461 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.901 Y96.874 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.345 Y96.286 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X114.788 Y95.699 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X114.232 Y95.112 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X113.676 Y94.524 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X113.120 Y93.937 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X112.564 Y93.350 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X112.008 Y92.762 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X111.452 Y92.175 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.896 Y91.587 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.340 Y91.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
; Completed path: dxf_entity_2_0_15pts

; Starting path: dxf_entity_3_0_22pts (normal)
G1 X140.000 Y91.000 F3000 ; Move to start of path
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y90.190 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y89.381 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y88.571 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y87.762 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y86.952 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y86.143 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y85.333 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y84.524 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y83.714 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y82.905 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y82.095 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y81.286 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y80.476 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y79.667 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y78.857 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y78.048 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y77.238 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y76.429 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y75.619 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y74.810 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X140.000 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
; Completed path: dxf_entity_3_0_22pts

; Starting path: dxf_entity_4_0_38pts (normal)
G1 X140.000 Y74.000 F3000 ; Move to start of path
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X139.189 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X138.378 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X137.568 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X136.757 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.946 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X135.135 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X134.324 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X133.514 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X132.703 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.892 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X131.081 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X130.270 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X129.459 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X128.649 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.838 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.027 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.216 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X125.405 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.595 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.784 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.973 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X122.162 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X121.351 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X120.541 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X119.730 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.919 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X118.108 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X117.297 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X116.486 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X115.676 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X114.865 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X114.054 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X113.243 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X112.432 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X111.622 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.811 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y74.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
; Completed path: dxf_entity_4_0_38pts

; Starting path: dxf_entity_5_0_22pts (normal)
G1 X110.000 Y74.000 F3000 ; Move to start of path
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y74.810 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y75.619 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y76.429 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y77.238 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y78.048 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y78.857 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y79.667 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y80.476 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y81.286 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y82.095 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y82.905 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y83.714 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y84.524 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y85.333 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y86.143 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y86.952 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y87.762 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y88.571 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y89.381 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y90.190 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X110.000 Y91.000 F3000 ; Move to next point
G1 Z0.1 F3000 ; Lower to weld height
G4 P500 ; Weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
; Completed path: dxf_entity_5_0_22pts

; Starting path: dxf_entity_0_0_7pts (frangible)
G1 X122.500 Y96.803 F3000 ; Move to start of path
G1 Z0.35 F3000 ; Lower to frangible weld height
G4 P500 ; Frangible weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X123.323 Y96.627 F3000 ; Move to next point
G1 Z0.35 F3000 ; Lower to frangible weld height
G4 P500 ; Frangible weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X124.159 Y96.521 F3000 ; Move to next point
G1 Z0.35 F3000 ; Lower to frangible weld height
G4 P500 ; Frangible weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X125.000 Y96.485 F3000 ; Move to next point
G1 Z0.35 F3000 ; Lower to frangible weld height
G4 P500 ; Frangible weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X125.841 Y96.521 F3000 ; Move to next point
G1 Z0.35 F3000 ; Lower to frangible weld height
G4 P500 ; Frangible weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X126.677 Y96.627 F3000 ; Move to next point
G1 Z0.35 F3000 ; Lower to frangible weld height
G4 P500 ; Frangible weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
G1 X127.500 Y96.803 F3000 ; Move to next point
G1 Z0.35 F3000 ; Lower to frangible weld height
G4 P500 ; Frangible weld for 0.5s
G1 Z1.5 F3000 ; Raise to low travel height
; Completed path: dxf_entity_0_0_7pts

; End of welding sequence
; Total paths processed: 7
; Total points processed: 368

; End sequence
G1 Z10 F600 ; Raise nozzle to high travel height
G28 X Y ; Home X and Y axes
M107 ; Turn off part cooling fan
M84 ; Disable steppers
; End of G-code
